clean up boot script setup

diff --git a/commands/xavier/boot_control/setup_boot_script b/commands/xavier/boot_control/setup_boot_script
--- a/commands/xavier/boot_control/setup_boot_script
+++ b/commands/xavier/boot_control/setup_boot_script
@@ -1,41 +1,223 @@
-#!/usr/bin/env bash
-read -r -d '' stuff_for_sudo <<'HEREDOC_NAME'
+#!/usr/bin/env sh
+"\"",`$(echo --% ' |out-null)" >$null;function :{};function dv{<#${/*'>/dev/null )` 2>/dev/null;dv() { #>
+echo "1.46.3"; : --% ' |out-null <#'; }; version="$(dv)"; deno="$HOME/.deno/$version/bin/deno"; if [ -x "$deno" ]; then  exec "$deno" run -q -A --no-lock "$0" "$@";  elif [ -f "$deno" ]; then  chmod +x "$deno" && exec "$deno" run -q -A --no-lock "$0" "$@";  fi; bin_dir="$HOME/.deno/$version/bin"; exe="$bin_dir/deno"; has () { command -v "$1" >/dev/null; } ;  if ! has unzip; then if ! has apt-get; then  has brew && brew install unzip; else  if [ "$(whoami)" = "root" ]; then  apt-get install unzip -y; elif has sudo; then  echo "Can I install unzip for you? (its required for this command to work) ";read ANSWER;echo;  if [ "$ANSWER" = "y" ] || [ "$ANSWER" = "yes" ] || [ "$ANSWER" = "Y" ]; then  sudo apt-get install unzip -y; fi; elif has doas; then  echo "Can I install unzip for you? (its required for this command to work) ";read ANSWER;echo;  if [ "$ANSWER" = "y" ] || [ "$ANSWER" = "yes" ] || [ "$ANSWER" = "Y" ]; then  doas apt-get install unzip -y; fi; fi;  fi;  fi;  if ! has unzip; then  echo ""; echo "So I couldn't find an 'unzip' command"; echo "And I tried to auto install it, but it seems that failed"; echo "(This script needs unzip and either curl or wget)"; echo "Please install the unzip command manually then re-run this script"; exit 1;  fi;  repo="denoland/deno"; if [ "$OS" = "Windows_NT" ]; then target="x86_64-pc-windows-msvc"; else :;  case $(uname -sm) in "Darwin x86_64") target="x86_64-apple-darwin" ;; "Darwin arm64") target="aarch64-apple-darwin" ;; "Linux aarch64") repo="LukeChannings/deno-arm64" target="linux-arm64" ;; "Linux armhf") echo "deno sadly doesn't support 32-bit ARM. Please check your hardware and possibly install a 64-bit operating system." exit 1 ;; *) target="x86_64-unknown-linux-gnu" ;; esac; fi; deno_uri="https://github.com/$repo/releases/download/v$version/deno-$target.zip"; exe="$bin_dir/deno"; if [ ! -d "$bin_dir" ]; then mkdir -p "$bin_dir"; fi;  if ! curl --fail --location --progress-bar --output "$exe.zip" "$deno_uri"; then if ! wget --output-document="$exe.zip" "$deno_uri"; then echo "Howdy! I looked for the 'curl' and for 'wget' commands but I didn't see either of them. Please install one of them, otherwise I have no way to install the missing deno version needed to run this code"; exit 1; fi; fi; unzip -d "$bin_dir" -o "$exe.zip"; chmod +x "$exe"; rm "$exe.zip"; exec "$deno" run -q -A --no-lock "$0" "$@"; #>}; $DenoInstall = "${HOME}/.deno/$(dv)"; $BinDir = "$DenoInstall/bin"; $DenoExe = "$BinDir/deno.exe"; if (-not(Test-Path -Path "$DenoExe" -PathType Leaf)) { $DenoZip = "$BinDir/deno.zip"; $DenoUri = "https://github.com/denoland/deno/releases/download/v$(dv)/deno-x86_64-pc-windows-msvc.zip";  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;  if (!(Test-Path $BinDir)) { New-Item $BinDir -ItemType Directory | Out-Null; };  Function Test-CommandExists { Param ($command); $oldPreference = $ErrorActionPreference; $ErrorActionPreference = "stop"; try {if(Get-Command "$command"){RETURN $true}} Catch {Write-Host "$command does not exist"; RETURN $false}; Finally {$ErrorActionPreference=$oldPreference}; };  if (Test-CommandExists curl) { curl -Lo $DenoZip $DenoUri; } else { curl.exe -Lo $DenoZip $DenoUri; };  if (Test-CommandExists curl) { tar xf $DenoZip -C $BinDir; } else { tar -Lo $DenoZip $DenoUri; };  Remove-Item $DenoZip;  $User = [EnvironmentVariableTarget]::User; $Path = [Environment]::GetEnvironmentVariable('Path', $User); if (!(";$Path;".ToLower() -like "*;$BinDir;*".ToLower())) { [Environment]::SetEnvironmentVariable('Path', "$Path;$BinDir", $User); $Env:Path += ";$BinDir"; } }; & "$DenoExe" run -q -A --no-lock "$PSCommandPath" @args; Exit $LastExitCode; <# 
+# */0}`;
+import { OperatingSystem } from "https://deno.land/x/quickr@0.6.72/main/operating_system.js"
+import { FileSystem, glob } from "https://deno.land/x/quickr@0.6.72/main/file_system.js"
+import run from "https://esm.sh/jsr/@david/dax@0.42.0"
+import { Console, clearAnsiStylesFrom, black, white, red, green, blue, yellow, cyan, magenta, lightBlack, lightWhite, lightRed, lightGreen, lightBlue, lightYellow, lightMagenta, lightCyan, blackBackground, whiteBackground, redBackground, greenBackground, blueBackground, yellowBackground, magentaBackground, cyanBackground, lightBlackBackground, lightRedBackground, lightGreenBackground, lightYellowBackground, lightBlueBackground, lightMagentaBackground, lightCyanBackground, lightWhiteBackground, bold, reset, dim, italic, underline, inverse, strikethrough, gray, grey, lightGray, lightGrey, grayBackground, greyBackground, lightGrayBackground, lightGreyBackground, } from "https://deno.land/x/quickr@0.6.72/main/console.js"
 
-echo '[Unit]
+// helpers
+const shellEscape = (arg)=>"'"+arg.replace(/'/g,`'"'"'`)+"'"
+const userName = Deno.env.get("USER")
+const home = Deno.env.get("HOME")
+
+// 
+// 
+// parameters
+// 
+// 
+
+const envVarsFile = FileSystem.makeAbsolutePath(`${home}/.zshrc`)
+// note: the .ignore is because we don't want this to be synced with git
+const pathToOnBootCommand          = FileSystem.makeAbsolutePath(`${FileSystem.thisFolder}/boot_command.ignore`)
+const pathToActualInfinteRunScript = FileSystem.makeAbsolutePath(`${FileSystem.thisFolder}/cv_dark_infinite_run.ignore.sh`)
+const pathToBootLogFile            = FileSystem.makeAbsolutePath(`${home}/boot.log`)
+const pathToOldBootLogFile         = FileSystem.makeAbsolutePath(`${home}/boot.old.log`)
+const projectFolder                = FileSystem.makeAbsolutePath(await FileSystem.walkUpUntil(".git/config"))
+const pathToMainPy                 = `${projectFolder}/main/main.py`
+const nameOfStartService           = "cv_dark_boot"
+
+const defaultBootCommand = `#!/usr/bin/env bash
+
+# Edit me as needed
+python3 ${shellEscape(pathToMainPy)} @WE_BLUE @BOARD=XAVIER @GPU=TENSOR_RT @CAMERA=REALSENSE @SHOWTIME
+`
+
+const contentsOfInfiniteRunScript = `#!/usr/bin/env bash
+
+# 
+# 
+#  !!! THIS IS A GENERATED FILE !!!
+#  EDIT THE REAL ONE INSIDE OF ${FileSystem.thisFile.replace(/\n/g,"")}
+#  then run that file
+# 
+
+# note: when the boot script runs NOTHING is setup
+#       this script:
+#       1. sets up all the normal user stuff
+#       2. logs all output to $HOME/boot.log
+#       3. runs the following IN A LOOP: ${pathToOnBootCommand.replace(/\n/g,"")}
+
+this_username=${shellEscape(userName)}
+this_home=${shellEscape(home)}
+boot_log=${shellEscape(pathToBootLogFile)}
+old_boot_log=${shellEscape(pathToOldBootLogFile)}
+
+# handle logging file
+rm -f "$old_boot_log"
+# copy old file
+if [ -f "$boot_log" ]
+then
+    cp "$boot_log" "$old_boot_log"
+fi
+rm -f "$boot_log"
+
+sudo -u "$this_username" -E this_username="$this_username" this_home="$this_home" -- bash -c ${shellEscape(`
+    while true
+    do
+        . ${shellEscape(envVarsFile)}
+        cd ${shellEscape(projectFolder)}
+        . ${shellEscape(pathToOnBootCommand)}
+        
+        echo "#"
+        echo "#"
+        echo "#"
+        echo "# PROCESS DIED"
+        echo "# [RESTARTING now]"
+        echo "#"
+        echo "#"
+        echo "#"
+    done
+`)} 2>>"$boot_log" 1>>"$boot_log"
+`
+
+// 
+// sanity checks
+// 
+    // if (!OperatingSystem.commonChecks.isLinux || OperatingSystem.commonChecks.isWsl) {
+    //     throw Error(`\n\nThis script is ONLY for the Jetson. DO NOT RUN IT ON YOUR PC.\n\n`)
+    // }
+    if (Deno.env.get("FORNIX_FOLDER")) {
+        throw Error(`\n\nDon't run this script inside of the project env! (commands/start)\nIt needs to know the jetsons real home folder, and the project env uses a fake home folder\n`)
+    }
+    if (!FileSystem.sync.info(pathToMainPy).isFile) {
+        throw Error(`\n\n\nI expected the main.py file to exist here:\n    ${pathToMainPy}\nBut it doesn't.\nOpen up the setup_boot_script.js file and fix that path to point to the actual file.\n\n`)
+    }
+    if (!FileSystem.sync.info(pathToActualInfinteRunScript).isFile) {
+        throw Error(`\n\n\nI was going to tell the system to run this file:\n    ${pathToActualInfinteRunScript}\nBut it doesn't exist.\nOpen up the setup_boot_script.js file and fix that path to point to the actual file.\n\n`)
+    }
+    if (!nameOfStartService.match(/^[a-zA-Z_][a-zA-Z0-9_]+$/)) {
+        throw Error(`\n\nInside of ${FileSystem.thisFile}.\nYou must have changed the nameOfStartService to something with invalid characters.\nIt needs to be a valid variable name\n`)
+    }
+    if (home != `/home/${userName}`) {
+        console.warn(`\n\nThere is something weird going on\nNormally ${cyan("$HOME")} is /home/$username (aka it would be ${`/home/${userName}`})\nBut this time ${cyan("$HOME")} was ${home}\n\nIF YOU'RE RUNNING THIS INSIDE OF THE PROJECT ENV (commands/start)\nTHATS A PROBLEM\nIf that^ home is a fake home folder, this is going to break the boot script\n\n`)
+        await new Promise(r=>setTimeout(r,14000))
+    }
+
+// 
+// 
+// note: everything below runs right-now
+// (but everything above sets what to do on-boot)
+// 
+// 
+
+    // 
+    // 
+    // (setup) generate files
+    // 
+    // 
+
+    // generate pathToOnBootCommand if it doesn't exist
+    if (!FileSystem.sync.info(pathToOnBootCommand).isFile) {
+        console.log(`\n\nGenerating ${pathToOnBootCommand}\n`)
+        FileSystem.sync.write({
+            path: pathToOnBootCommand,
+            data: defaultBootCommand,
+        })
+    }
+    // ensure those scripts are executable
+    await FileSystem.addPermissions({
+        path: pathToOnBootCommand,
+        permissions: {
+            owner: {
+                canExecute: true,
+            },
+            group: {
+                canExecute: true,
+            },
+            other: {
+                canExecute: true,
+            }
+        },
+    })
+
+    // generate pathToActualInfinteRunScript if it doesn't exist
+    console.log(`\n\nGenerating ${pathToActualInfinteRunScript}\n`)
+    FileSystem.sync.write({
+        path: pathToActualInfinteRunScript,
+        data: contentsOfInfiniteRunScript,
+    })
+    // ensure those scripts are executable
+    await FileSystem.addPermissions({
+        path: pathToActualInfinteRunScript,
+        permissions: {
+            owner: {
+                canExecute: true,
+            },
+            group: {
+                canExecute: true,
+            },
+            other: {
+                canExecute: true,
+            }
+        },
+    })
+    
+    console.log(`Ensuring boot log files exist:`)
+    await FileSystem.ensureIsFile(pathToBootLogFile)
+    console.log(`   - ${cyan(pathToBootLogFile)}`)
+    await FileSystem.ensureIsFile(pathToOldBootLogFile)
+    console.log(`   - ${cyan(pathToOldBootLogFile)}`)
+
+// 
+// 
+// actually register the service
+// 
+// 
+const onBootRegistration = `[Unit]
 Description=CV Dark Boot
 After=network.target
 
 [Service]
-ExecStart=sudo /home/xavier/repos/cv_dark/commands/xavier/boot_control/cv_dark_infinite_run
+ExecStart=sudo -- ${shellEscape(pathToActualInfinteRunScript)}
 
 [Install]
 WantedBy=default.target
-' > /etc/systemd/system/cv_dark_boot.service
+`
 
-echo "#"
-echo "# starting services"
-echo "#"
-sudo systemctl enable cv_dark_boot
-sudo systemctl start cv_dark_boot
+const targetPath = `/etc/systemd/system/${nameOfStartService}.service`
+console.log(`\nInstalling service\n    name: ${cyan(nameOfStartService)}\n    installing to: ${yellow(targetPath)}\n`)
+// NOTE: I would normally do these things using JS/Deno, but they need sudo permission
+//       and one way to do that is run them in a shell script
+const actionsThatNeedSudo = `
+    echo "pipefail means that if any command fails, the script will stop" > /dev/null
+    set -o pipefail
 
-HEREDOC_NAME
+    echo ${shellEscape(onBootRegistration)} > ${shellEscape(targetPath)}
 
-echo "#"
-echo "# writing to /etc/systemd/system/xavier_boot.service"
-echo "#"
-sudo bash -c "$stuff_for_sudo"
+    echo "#"
+    echo "# starting services"
+    echo "#"
+    systemctl enable ${nameOfStartService}
+    systemctl start ${nameOfStartService}
+`
 
-echo "#"
-echo "# ensuring executable"
-echo "#"
-filepath="/home/xavier/repos/cv_dark/commands/xavier/boot_control/boot_command.ignore"
-if ! { [ -f "$filepath" ] && [ -r "$filepath" ] && [ -x "$filepath" ]; }
-then
-    echo 'NOTE: change this file if this bot uses the ZED camera'
-    echo 'file: '"$filepath"
-    echo '
-        python3 "/home/xavier/repos/cv_dark/main/main.py" @WE_BLUE @BOARD=XAVIER @GPU=TENSOR_RT @CAMERA=REALSENSE @SHOWTIME
-    ' > "$filepath"
-    chmod ugo+x "$filepath"
-fi
-echo "done; restart should now work"
+try {
+    var { code: exitCode } = await run`sudo bash -c ${actionsThatNeedSudo}`
+} catch (error) {
+    
+}
+var success = exitCode == 0
+if (!sucess) {
+    throw Error(`\n\nFailed: See above for details. For some reason the setup failed.`)
+}
+
+console.log(`
+
+Done. Restart should now trigger the boot script to run in an infinite loop.
+    ${green`boot script:`} ${pathToOnBootCommand}
+    ${green`boot log:`} ${pathToBootLogFile}
+    
+`)
+// (this comment is part of deno-guillotine, dont remove) #>
